const _soh = "01 ";
const _protocol = "4E 30 ";
const _eol = "04";
const _tab = "09 ";

/*
To pass a number to the Ultrix router over the GVG protocol, a handful of 
conversions need to take place.
  1.) Decimal -> Hex e.x.: 15 -> 0x0F
  2.) Hex to 4 char ASCII string e.x. 0x0F -> 000F
  3.) ASCII string to hex e.x. 000F -> 30 30 30 46
*/
String _gvgConvertNumber(int number) {
  String hexString = number.toRadixString(16);
  String outputString = "";

  while (hexString.length < 4) {
    hexString = "0$hexString";
  }

  hexString = hexString.toUpperCase();

  for (int i = 0; i < hexString.length; i++) {
    outputString += "${hexString.codeUnitAt(i).toRadixString(16)} ";
  }

  return outputString;
}

/*
The checksum is generated by following these steps:
  1.) Sum every hex value given
  2.) Bitwise and to ensure it is not larger than 8 bits.
  3.) Find the 2s compliment
  4.) Perform the gvg number conversion and remove the leading 0x30s.
*/
String _gvgChecksum(String preChecksum) {
  List<String> byteList = preChecksum.split(" ");
  int total = 0;

  // byteList - 1 is used because the given String will have a trailing space.
  for (int i = 0; i < byteList.length - 1; i++) {
      String temp = byteList[i];
      total += int.parse("0x$temp");
  }
  
  total = total & 0xFF;
  total = (0x100 - total) & 0xFF;

  String checksum = _gvgConvertNumber(total).substring(6);
  return checksum;
}

String take(int destination, int source) {
  String take = "54 49 ";
  
  //GVG Protocol counts from zero.
  destination = destination - 1;
  source = source - 1;

  String destHex = _gvgConvertNumber(destination);
  String sourceHex = _gvgConvertNumber(source);

  String takeCommand = "$_protocol$take$_tab$destHex$sourceHex";
  String checksum = _gvgChecksum(takeCommand);
  takeCommand = "$_soh$takeCommand$checksum$_eol";
  return takeCommand;
}

String queryDestination() {
  String command = "51 4E 09 44 ";
  command = "$_protocol$command";

  String checksum = _gvgChecksum(command);
  command = "$_soh$command$checksum$_eol";
  return command;
}

String querySource() {
  String command = "51 4E 09 53 ";
  command = "$_protocol$command";

  String checksum = _gvgChecksum(command);
  command = "$_soh$command$checksum$_eol";
  return command;
}